image: Ubuntu  

stack: jdk 11  

branches:
  only:
    - master  

build: off  

install:
    - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - chmod +x gradlew
  - Dselenide.headless = true
  - ./gradlew test --info 
